import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.PrintWriter;

import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tantianbao
 */
public class BreadFactoryFrame extends javax.swing.JFrame {

    private BreadCollection breadFactory;

    /**
     * Creates new form BreadFactoryFrame
     */
    public BreadFactoryFrame() {
        initComponents();
        breadFactory = new BreadCollection();
        breadFactory.initAmountOfFlour();
    }

    private void getNumOfLoaves() {
        JTextField[] inputs = {lblPlain, lblWholemeal, lblRaisin, lblBanana, lblCorn};

        for (int i = 0; i < breadFactory.getNumOfBreads(); i++) {
            breadFactory.getBread(i).setNumOfLoaves(Integer.parseInt(inputs[i].getText()));
        }
    }

    public void displayCosts() {
        String msg = "Type\tNumber of Loaves\tTotal Cost\n";
        msg += "====\t================\t=============";

        for (int i = 0; i < breadFactory.getNumOfBreads(); i++) {
            Bread b = breadFactory.getBread(i);
            double costs = b.getNumOfLoaves()*b.getAmtOfFlour()*breadFactory.getCostOfFLour();
            msg += b.getName() + "\t" + b.getNumOfLoaves() + "\t\t$" + costs + "\n";
        }
        jScrollPane.setText(msg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCostOfFlour = new javax.swing.JTextField();
        pnlNumOfFlour = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblRaisin = new javax.swing.JTextField();
        lblPlain = new javax.swing.JTextField();
        lblWholemeal = new javax.swing.JTextField();
        lblBanana = new javax.swing.JTextField();
        lblCorn = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane = new javax.swing.JTextArea();
        btnSave = new javax.swing.JButton();
        btnRetrieve = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bread Factory");

        jLabel1.setText("Cost of Flour ($/gram):");

        pnlNumOfFlour.setBorder(javax.swing.BorderFactory.createTitledBorder("Number of Loaves"));

        jLabel2.setText("Plain Loaf");

        jLabel3.setText("Wholemeal Loaf");

        jLabel4.setText("Raisin Loaf");

        jLabel5.setText("Banana Loaf");

        jLabel6.setText("Corn Loaf");

        javax.swing.GroupLayout pnlNumOfFlourLayout = new javax.swing.GroupLayout(pnlNumOfFlour);
        pnlNumOfFlour.setLayout(pnlNumOfFlourLayout);
        pnlNumOfFlourLayout.setHorizontalGroup(
            pnlNumOfFlourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNumOfFlourLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNumOfFlourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlNumOfFlourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRaisin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPlain, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWholemeal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBanana, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCorn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        pnlNumOfFlourLayout.setVerticalGroup(
            pnlNumOfFlourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNumOfFlourLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlNumOfFlourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(1, 1, 1)
                .addGroup(pnlNumOfFlourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblWholemeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlNumOfFlourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblRaisin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlNumOfFlourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblBanana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlNumOfFlourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblCorn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        jScrollPane.setColumns(20);
        jScrollPane.setRows(5);
        jScrollPane1.setViewportView(jScrollPane);

        btnSave.setText("Save to File");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnRetrieve.setText("Retrieve From File");
        btnRetrieve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrieveActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRetrieve)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlNumOfFlour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(41, 41, 41)
                                .addComponent(txtCostOfFlour, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnCalculate)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCalculate)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCostOfFlour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(pnlNumOfFlour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnRetrieve)
                    .addComponent(btnClear))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        try {
            breadFactory.setCostOfFLour(
                Double.parseDouble(txtCostOfFlour.getText())
            );
            getNumOfLoaves();
            displayCosts();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error! ", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        lblBanana.setText("");
        lblCorn.setText("");
        lblPlain.setText("");
        lblRaisin.setText("");
        lblWholemeal.setText("");
        jScrollPane.setText("");
        txtCostOfFlour.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // try {
        //     PrintWriter pw = new PrintWriter(new FileWriter("breadTxt.txt"));
        //     pw.println(breadFactory.getCostOfFLour());
        //     for (int i = 0; i < breadFactory.getNumOfBreads(); i++) {
        //         Bread b = breadFactory.getBread(i);
        //         pw.println(b.getName()+ "," + b.getNumOfLoaves());
        //     }
        //     pw.close();
        // } catch (Exception e) {
        //     JOptionPane.showMessageDialog(null, e.getMessage());
        // }
        try {
            ObjectOutputStream outputStream = new ObjectOutputStream(new FileOutputStream("breadFactory.dat"));
            outputStream.writeObject(breadFactory);
            outputStream.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnRetrieveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrieveActionPerformed
        // try {
        //     BufferedReader br = new BufferedReader(new FileReader("breadTxt.txt"));
        //     String t = br.readLine();
        //     breadFactory.setCostOfFLour(Double.parseDouble(t));
        //     String [] temp;
        //     for (int i=0;i < breadFactory.getNumOfBreads();i++) {
        //         t = br.readLine();
        //         temp = t.split(",");
        //         Bread b = breadFactory.getBread(i);
        //         b.setNumOfLoaves(Integer.parseInt(temp[1]));
        //     }
        //     br.close();
        //     // update ui
        //     txtCostOfFlour.setText(breadFactory.getCostOfFLour()+"");
        //     JTextField [] inputs = {lblPlain, lblWholemeal, lblRaisin, lblBanana, lblCorn};

        //     for(int i=0; i <breadFactory.getNumOfBreads(); i++) {
        //         inputs[i].setText(""+breadFactory.getBread(i).getNumOfLoaves());
        //     }
        //     displayCosts();
        // } catch (Exception e) {
        //     // TODO Auto-generated catch block
        //     JOptionPane.showMessageDialog(null, e.getMessage());
        // } 
        try {
            ObjectInputStream inputStream = new ObjectInputStream(new FileInputStream("breadFactory.dat"));
            breadFactory = (BreadCollection) inputStream.readObject();
            inputStream.close();
            // update ui
            txtCostOfFlour.setText(breadFactory.getCostOfFLour()+"");
            JTextField [] inputs = {lblPlain, lblWholemeal, lblRaisin, lblBanana, lblCorn};

            for(int i=0; i <breadFactory.getNumOfBreads(); i++) {
                inputs[i].setText(""+breadFactory.getBread(i).getNumOfLoaves());
            }
            displayCosts();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnRetrieveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BreadFactoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BreadFactoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BreadFactoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BreadFactoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BreadFactoryFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnRetrieve;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextArea jScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lblBanana;
    private javax.swing.JTextField lblCorn;
    private javax.swing.JTextField lblPlain;
    private javax.swing.JTextField lblRaisin;
    private javax.swing.JTextField lblWholemeal;
    private javax.swing.JPanel pnlNumOfFlour;
    private javax.swing.JTextField txtCostOfFlour;
    // End of variables declaration//GEN-END:variables
}
